name: Rust

on:
  push:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Continuous Integration Testing
    if: ${{ contains(github.event.head_commit.message, '[ci]') }}

    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --verbose
